urls.py
from django.conf.urls import patterns, url
from views import *

urlpatterns = patterns(
    '',
    url(r'^$', Index.as_view(), name='index'),
    url(r'^project/new', create_project, name='project-new'),
    url(r'^project/(?P<pk>\d+)/edit', EditProject.as_view(), name='project-edit'),
    url(r'^project/(?P<pk>\d+)$', project_detail, name='project-detail'),
    url(r'^person/(?P<pk>\d+)$', PersonDetailView.as_view(), name='person-detail'),
    url(r'^task/new$', create_task, name='task-new'),
    url(r'^task/edit$', edit_task, name='task-edit'),
    url(r'^get_users$', get_users, name='get-users'),
)

models.py
from datetime import date, timedelta
from django.contrib.auth.models import User
from django.conf import settings
from django.db import models


# Redefine the User model to use a cleaner name rather than the
# username itself, which may be difficult to interpret
def user_unicode_patch(self):
    return u'%s, %s (%s)' % (self.last_name, self.first_name, self.username)

User.__unicode__ = user_unicode_patch


class Group(models.Model):
    name = models.CharField(max_length=200, primary_key=True)
    manager = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True)
    internal = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name


class People(models.Model):
    name = models.OneToOneField(settings.AUTH_USER_MODEL)
    group = models.ForeignKey(Group)

    class Meta:
        unique_together = ('name', 'group',)
        permissions = (
            ('view_people', 'Can view people'),
            ('modify_people', 'Can create, edit, and delete people'),
        )

    def __unicode__(self):
        return "%s, %s (%s)" % (self.name.last_name, self.name.first_name, self.group.name)

    def full_name(self):
        return "%s %s" % (self.name.first_name, self.name.last_name)
        
    def full_name_lastnamefirst(self):
        return "%s, %s" % (self.name.last_name, self.name.first_name)
    
    def lead_count(self):
        return self.worker_set.filter(owner=True).count()

    def task_count(self):
        return TaskWorker.objects.filter(worker__person=self).count()

    def two_wk_task_count(self):
        return TaskWorker.objects.filter(worker__person=self, task__due_date__range=[
            date.today(),
            date.today() + timedelta(14)
        ]).count()


class Program(models.Model):
    name = models.CharField(max_length=500)
    description = models.TextField()
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        permissions = (
            ('modify_program', 'Can create, edit, and delete programs'),
        )

    def __unicode__(self):
        return self.name


class Project(models.Model):
    HIGH = 'HI'
    STANDARD = 'ST'
    LOW = 'LO'
    PRIORITY_CHOICES = (
        (HIGH, 'High'),
        (STANDARD, 'Standard'),
        (LOW, 'Low')
    )

    ACTIVE = 'A'
    ON_HOLD = 'O'
    WARRANTY = 'W'
    MAINTENANCE = 'M'
    COMPLETED = 'C'
    STATUS_CHOICES = (
        (ACTIVE, 'Active'),
        (ON_HOLD, 'On hold'),
        (WARRANTY, 'Warranty'),
        (MAINTENANCE, 'Maintenance'),
        (COMPLETED, 'Completed')
    )

    name = models.CharField(max_length=500)
    requester = models.ForeignKey(People, related_name="person_requester")
    project_manager = models.ForeignKey(People, related_name="person_project_manager")
    program = models.ForeignKey(Program)
    description = models.TextField()
    date_added = models.DateField(auto_now_add=True)
    start_date = models.DateField()
    due_date = models.DateField(null=True, blank=True)
    date_complete = models.DateField(null=True, blank=True)
    sharepoint_ticket = models.URLField(null=True, blank=True)
    priority = models.CharField(null=True, choices=PRIORITY_CHOICES, default=STANDARD, max_length=2)
    status = models.CharField(choices=STATUS_CHOICES, default=ACTIVE, max_length=1)

    class Meta:
        permissions = (
            ('view_project', 'Can view projects'),
            ('modify_project', 'Can create, edit, and delete projects'),
        )

    def __unicode__(self):
        return self.name

    def completed_tasks(self):
        """
        Return the number of completed tasks in a project.
        """
        return self.task_set.exclude(date_complete=None)

    def est_completion_date(self):
        """
        Iterate through the tasks in a project, return the latest due date as
        the project completion estimate. If no tasks are yet assigned, return
         "No Estimate".
        """
        if self.task_set.all().count() is 0:
            return "No estimate"
        else:
            due_dates = []
            for task in self.task_set.all():
                if task.due_date is None:
                    continue
                else:
                    due_dates.append(task.due_date)
            if len(due_dates) == 0:
                return "No estimate"
            else:
                return max(due_dates)
    
    def next_tasks(self):
        """
        Return a list of the next tasks due plus due dates.
        """
        due_date_list = self.task_set.exclude(due_date=None).values('due_date')  # min() returns a dict, pulling the datetime value out
        if not due_date_list:
            return due_date_list
        next_due_date = min(due_date_list)['due_date'] 
        return self.task_set.filter(due_date=next_due_date)


class Worker(models.Model):
    project = models.ForeignKey(Project)
    person = models.ForeignKey(People)
    date_added = models.DateField(auto_now_add=True)
    start_date = models.DateField(null=True, blank=True)
    date_complete = models.DateField(null=True, blank=True)
    percent_committed = models.IntegerField(null=True, blank=True)
    owner = models.BooleanField(default=False)

    class Meta:
        unique_together = ('project', 'person',)

    def __unicode__(self):
        return "%s (%s) - %s" % (self.person.full_name(), self.person.group.name, self.project.name)


class Task(models.Model):
    project = models.ForeignKey(Project)
    name = models.CharField(max_length=500)
    description = models.TextField()
    date_added = models.DateField(auto_now_add=True)
    start_date = models.DateField(null=True, blank=True)
    due_date = models.DateField(null=True, blank=True)
    date_complete = models.DateField(null=True, blank=True)
    status_on_hold = models.BooleanField(default=False)
    status_waiting = models.BooleanField(default=False)

    class Meta:
        unique_together = ('name', 'project',)
        permissions = (
            ('view_task', 'Can view tasks'),
            ('modify_task', 'Can create, edit, and delete tasks'),
        )

    def __unicode__(self):
        return "%s - %s" % (self.name, self.project.name)

    def status(self):
        if self.date_complete is not None:
            return 'Complete'
        elif self.status_waiting:
            return 'Waiting on\n external party'
        elif self.status_on_hold:
            return 'On hold'
        elif TaskDependency.objects.filter(blocked_task=self).filter(blocking_task__date_complete=None).exists():
            return 'Queued'
        else:
            return 'Active'


class TaskDependency(models.Model):
    blocking_task = models.ForeignKey(Task, related_name="blocking_task")
    blocked_task = models.ForeignKey(Task, related_name="blocked_task")

    class Meta:
        unique_together = ('blocking_task', 'blocked_task',)

    def __unicode__(self):
        return "%s - %s" % (self.blocking_task, self.blocked_task)


class TaskWorker(models.Model):
    task = models.ForeignKey(Task)
    worker = models.ForeignKey(Worker)

    class Meta:
        unique_together = ('task', 'worker',)

    def __unicode__(self):
        return "%s (%s) - %s - %s" % (self.worker.person.full_name(), self.worker.person.group.name, self.worker.project.name, self.task.name)

forms.py
from django import forms
from django.db.models import Q
from pm.models import Program, Project, People, Task, Worker, TaskDependency
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Div, Field, HTML


class ProjectForm(forms.Form):
    name = forms.CharField(max_length=500)
    requester = forms.ModelChoiceField(People.objects.all())
    project_manager = forms.ModelChoiceField(People.objects.filter(group__internal=True))
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 10, 'cols': 60}))
    start_date = forms.DateField()
    due_date = forms.DateField(required=False)
    date_complete = forms.DateField(required=False)
    sharepoint_ticket = forms.URLField(required=False)
    priority = forms.ChoiceField(choices=Project.PRIORITY_CHOICES, initial=Project.STANDARD)
    status = forms.ChoiceField(choices=Project.STATUS_CHOICES)
    program = forms.ModelChoiceField(Program.objects.all(), empty_label=None, initial="None")
    workers = forms.ModelMultipleChoiceField(queryset=People.objects.all())

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = "create_project"
        self.helper.form_action = "pm:project-new"
        self.helper.add_input(Submit('submit', 'Submit'))
        self.helper.layout = Layout(
            Div(
                Div(Field('name'), css_class='col-sm-6'),
                Div(Field('requester'), css_class='col-sm-3'),
                Div(Field('project_manager'), css_class='col-sm-3'),
                css_class='row',
            ),
            Div(
                Div(Field('description'), css_class='col-sm-6'),
                Div(
                    Div(
                        Div(Field('start_date'), css_class='col-sm-6 datemask'),
                        Div(Field('program'), css_class='col-sm-6'),
                        css_class='row',
                    ),
                    Div(
                        Div(Field('due_date'), css_class='col-sm-6 datemask'),
                        Div(Field('status'), css_class='col-sm-6'),
                        css_class='row',
                    ),
                    Div(
                        Div(Field('date_complete'), css_class='col-sm-6 datemask'),
                        Div(Field('priority'), css_class='col-sm-6'),
                        css_class='row',
                    ),
                    css_class='col-sm-6',
                ),
                css_class='row',
            ),
            Div(
                Div(Field('sharepoint_ticket'), css_class='col-sm-6'),
                Div(Field('workers'), css_class='col-sm-6'),
                css_class='row',
            )
        )


class TaskForm(forms.Form):
    project = forms.ModelChoiceField(queryset=Project.objects.all(), empty_label=None)
    name = forms.CharField()
    start_date = forms.DateField(input_formats=['%m-%d-%Y'])
    due_date = forms.DateField(input_formats=['%m-%d-%Y'], required=False)
    date_complete = forms.DateField(input_formats=['%m-%d-%Y'], required=False)
    status_on_hold = forms.BooleanField(required=False, label='On hold')
    status_waiting = forms.BooleanField(required=False, label='Waiting on external party')
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 4, 'cols': 60}), required=False)
    worker = forms.ModelMultipleChoiceField(queryset=People.objects.none())
    blocked_by = forms.ModelMultipleChoiceField(queryset=Task.objects.none(), required=False)
    pk = forms.IntegerField(required=False)

    def __init__(self, *args, **kwargs):
        self.project_id = kwargs.pop('project_id')
        super(TaskForm, self).__init__(*args, **kwargs)
        self.fields['worker'].queryset = People.objects.filter(Q(worker__project=self.project_id) & Q(group__internal=True))
        self.fields['blocked_by'].queryset = Task.objects.filter(project=self.project_id)

        self.helper = FormHelper()
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = "col-md-3"
        self.helper.field_class = "col-md-9"
        self.helper.form_id = "create-task"
        self.helper.form_action = "pm:task-new"
        self.helper.add_input(Submit('submit', 'Submit'))
        self.helper.layout = Layout(
            Div(
                Div(Field('name'), css_class='col-lg-3 col-sm-6'),
                Div(Field('start_date'), css_class='col-lg-3 col-sm-6 datemask'),
                Div(Field('due_date'), css_class='col-lg-3 col-sm-6 datemask'),
                Div(Field('status_on_hold'), Field('status_waiting'), css_class='col-lg-3 col-sm-6'),
                css_class='row',
            ),
            Div(
                Div(Field('description'), css_class='col-lg-3 col-sm-6'),
                Div(Field('worker'), css_class='col-lg-3 col-sm-6'),
                Div(Field('blocked_by'), css_class='col-lg-3 col-sm-6'),
                Div(Field('project'), css_class='col-lg-3 col-sm-6'),
                css_class='row',
            ),
        )

templates/pm/person_detail.html
{% extends "pm/base.html" %}

{% block title %}Person Detail - {{ person.full_name }}{% endblock title %}

{% block content-header %}Person Detail - <b>{{ person.full_name }}</b> ({{ person.group.name }}){% endblock content-header %}

{% block content %}
<div class="row">
    <div class="col-md-4">
        <div class="box box-solid">
            <div class="box-header">
                <i class="fa fa-briefcase"></i>
                <h3 class="box-title">Projects</h3>
            </div>
            <div class="box-body">
                <table class="table">
                    <tr>
                        <th class="vcenter">Project</th>
                        <th class="center vcenter">Lead</th>
                        <th class="center vcenter">Team Members</th>
                    </tr>
                    {% for worker in person.worker_set.all %}
                    <tr>
                        <td>{{ worker.project.name }}</td>
                        <td class="center">{% if worker.owner %}<i class="fa fa-check"></i>{% else %}&nbsp;{% endif %}</td>
                        <td>{% for w in worker.project.worker_set.all %}{{ w.person.full_name }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="box box-solid">
            <div class="box-header">
                <i class="fa fa-tasks"></i>
                <h3 class="box-title">Tasks</h3>
            </div>
            <div class="box-body">
                <table class="table">
                    <tr>
                        <th class="center vcenter" width="12%">Project</th>
                        <th class="center vcenter">Task Title & Description</th>
                        <th class="center vcenter" width="12%">Start</th>
                        <th class="center vcenter" width="12%">Due</th>
                        <th class="center vcenter" width="12%">Assigned To...</th>
                    </tr>
                    {% for worker in person.worker_set.all %}
                    {% for t in worker.taskworker_set.all %}
                    <tr>
                        <td>{{ t.task.project.name }}</td>
                        <td><b>{{ t.task.name }}</b> - {{ t.task.description }}</td>
                        <td class="center">{{ t.task.start_date | date:"M. jS" }}</td>
                        <td class="center">{{ t.task.due_date | date:"M. jS" }}</td>
                        <td>{% for w in t.task.taskworker_set.all %}{{ w.worker.person.full_name }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
                    </tr>
                    {% endfor %}
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% debug %}

templates/pm/project_detail.html
{% extends "pm/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Project Detail - {{ project.name }}{% endblock title %}

{% block content-header %}<b>{{ project.name }}</b> ({{ project.program.name }}){% endblock content-header %}

{% block section_id %}project-detail{% endblock section_id %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        <div class="box">
            <div class="box-header">
                <i class="ion ion-clipboard"></i>
                <h3 class="box-title">Description</h3>
            </div>
            <div class="box-body">{{ project.description | linebreaksbr }}</div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="box details">
            <div class="box-header">
                <i class="fa fa-list-ul"></i>
                <h3 class="box-title">Project Details</h3>
                <div class="box-tools pull-right">
                    <button class="btn btn btn-default btn-sm edit-project"><i class="fa fa-pencil"></i></button>
                </div>
            </div>
            <div class="box-body">
                <table class="table table-condensed">
                    <tr>
                        <td>ID:</td>
                        <td>{{ project.id | stringformat:"04d" }}</td>
                    </tr>
                    <tr>
                        <td>Requester:</td>
                        <td>{{ project.requester.full_name }}</td>
                    </tr>
                    <tr>
                        <td>Proj. Manager:</td>
                        <td>{{ project.project_manager.full_name }}</td>
                    </tr>
                    <tr>
                        <td>Assigned to:</td>
                        <td>{% for worker in project.worker_set.all %}<span class="{% if worker.owner %}bold{% endif %} {% if not worker.person.group.internal %}text-muted{% endif %}">{{ worker.person.full_name }}</span>{% if not forloop.last %}, {% endif %}{% endfor %}</td>
                    </tr>
                    <tr>
                        <td>Start Date:</td>
                        <td>{{ project.start_date }}</td>
                    </tr>
                    <tr>
                        <td>Due Date:</td>
                        <td>{{ project.due_date }}</td>
                    </tr>
                    {% if project.sharepoint_ticket %}
                    <tr>
                        <td>URL:</td>
                        <td><a href="{{ project.sharepoint_ticket }}" target="_blank">Sharepoint ticket</a></td>
                    </tr>
                    {% endif %}
                    <tr>
                        <td>Status:</td>
                        <td>{{ project.get_status_display }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="row new-task">
    <div class="col-md-12">
        <div class="alert alert-danger alert-dismissable">
            <h4>Error!</h4>
            <p>An error was encountered while saving the form. Please try again shortly.</p>
        </div>
    </div>
    <div class="col-md-12">
        <div class="alert alert-success alert-dismissable">
            <i class="fa fa-check"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <p>Task successfully entered!</p>
        </div>
    </div>
    <div class="col-md-12">
        <div class="box box-solid box-warning">
            <div class="box-header">
                <h3 class="box-title">New Task</h3>
            </div>
            <div class="box-body">
                {% crispy taskform %}
            </div>
        </div>
    </div>
</div>
<div class="row tasks">
    <div class="col-md-12">
        <div class="alert alert-danger alert-dismissable">
            <h4>Errors</h4>
            <div class="errors"></div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="alert alert-success alert-dismissable">
            <i class="fa fa-check"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <p>Task successfully edited! (Reload to see changes)</p>
        </div>
    </div>
    <div class="col-md-12">
        <div class="box">
            <div class="box-header">
                <i class="fa fa-tasks"></i>
                <h3 class="box-title">Tasks</h3>
                <div class="box-tools pull-right">
                    <button class="btn btn-default btn-sm add-task-button"><i class="fa fa-plus"></i> Add task</button>
                </div>
            </div>
            <div class="box-body">
                {% include "pm/task.html" %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block custom_js %}
"use strict";

var taskFunc = function() {
    $(".new-task").show();
    $(".new-task .box").show();
    $(".new-task .alert-danger").hide();
    $(".new-task .alert-success").hide();
}

$(document).keydown(function(e) {
    // "n" or "N" opens new task window
    if(e.which == 78 && document.activeElement.tagName.toLowerCase() === "body") {
        taskFunc();
    }

    // "esc" hides new task window
    if(e.which == 27) {
        $(".new-task").hide();
    }
});
$('.add-task-button').on('click', taskFunc);

//
// AJAX CONTENT
//

// ### SEE https://docs.djangoproject.com/en/dev/ref/csrf/ FOR DETAILS ON THE FOLLOWING ###
// The following code ensures that the CSRF token is properly inserted in the header of the AJAX request

var csrftoken = $.cookie('csrftoken');

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}

$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});

// ### END AJAX HEADER CONTENT

// new task
function process_submit (event) {
    event.preventDefault();

    $.ajax({
            url: "{% url 'pm:task-new' %}",
            type: "POST",
            dataType: "json",
            data: $('#create-task').serialize(),
            success: function(data) {
                if(!(data['success'])) {
                    $('#create-task').replaceWith(data['form_html']);
                    $('#create-task').on('submit', process_submit);  // need to bind the function to the new element
                    $('.datemask input')
                    // date masking
                        .inputmask('mm-dd-yyyy', {"placeholder": "mm-dd-yyyy"})
                    // add calendar icon
                        .wrap('<div class="input-group"></div>')
                        .before('<div class="input-group-addon"><i class="fa fa-calendar"></i></div>');

                } else {
                    $('.new-task .box').hide();
                    $('.new-task .alert-success').show();
                    $('#create-task').trigger('reset'); // remove the value from the input
                }
            },
            error: function(xhr,errmsg,err) {
                $('.new-task .alert-danger').show();
                console.log(xhr.status + ": " + xhr.responseText);
            }
        });
};

$('#create-task').on('submit', process_submit);

$('.datemask input, .datepicker input')
// date masking
    .inputmask('mm-dd-yyyy', {"placeholder": "mm-dd-yyyy"})
    .daterangepicker({
        singleDatePicker: true,
        showDropdowns: true
    });

// add calendar icon
$('.datemask input')
    .wrap('<div class="input-group"></div>')
    .before('<div class="input-group-addon"><i class="fa fa-calendar"></i></div>');

$('tr.task td.status').hover(function() {
    if( $(this).children('.controls').is(':hidden') ) {
        $(this).children('small').toggle();
        $(this).children('.edit').toggle();
    }
});

// remove extra padding around checkboxes
$('.new-task .checkbox').css({'padding-top': '0', 'padding-bottom': '7px'}).parents('div.form-group').css({'margin-bottom': '0'});

$('.details').hover(function() { $(this).find('button.edit-project').show(); },
                    function() { $(this).find('button.edit-project').hide(); });
$('button.edit-project').click(function() { window.open('{% url 'admin:pm_project_change' project.id %}', '_blank'); });

$('tr.task td.status .edit').click(function() {
    $(this).hide();
    $(this).siblings('.controls').show();
    $(this).parents('tr').children('td:not(.status)').children(':input, .input-help').show();
    $(this).parents('tr').children('td:not(.status)').children('.txt').hide();
});

$('tr.task td.status .controls button').click(function() {
    var controls = $(this).parents('.controls');
    var this_tr = $(this).parents('tr');
    var i = $(this).parents('.task').find(':input').serialize();

    if( $(this).hasClass('submit') ) {
        $.ajax({
                url: "{% url 'pm:task-edit' %}",
                type: "POST",
                dataType: "json",
                data: i,
                success: function(data) {
                    if(!(data['success'])) {
                        // show errors
                        $('.tasks .errors').empty();
                        $('.tasks .errors').html(data['failure']);
                        $('.tasks .alert-danger').show();
                    } else {
                        controls.hide();
                        controls.siblings('.edit').show();
                        this_tr.children('td:not(.status)').children(':input, .input-help').hide();
                        this_tr.children('td:not(.status)').children('.txt').show();

                        $('.tasks .alert-danger').empty();
                        $('.tasks .alert-danger').hide();
                        $('.tasks .alert-success').show();
                    }
                },
                error: function(xhr,errmsg,err) {
                    $('.new-task .alert-danger').show();
                    console.log(xhr.status + ": " + xhr.responseText);
                }
            });
    } else {
    // Cancel pushed
        controls.hide();
        controls.siblings('.edit').show();
        this_tr.children('td:not(.status)').children(':input, .input-help').hide();
        this_tr.children('td:not(.status)').children('.txt').show();
    }
});

{% for task in project.task_set.all %}
$(".task-{{ task.pk }} select[name='worker']").val([{% for taskworker in task.taskworker_set.all %}{{ taskworker.worker.person.pk }}{% if not forloop.last %}, {% endif %}{% endfor %}]);{% endfor %}
{% for task in project.task_set.all %}
$(".task-{{ task.pk }} select[name='blocked_by']").val([{% for t in task.blocked_task.all %}{{ t.blocking_task.pk }}{% if not forloop.last %}, {% endif %}{% endfor %}]);{% endfor %}
{% endblock %}

templates/pm/project_new.html
{% extends "pm/base.html" %}
{% load crispy_forms_tags %}

{% block title %}New Project{% endblock %}

{% block content-header %}Create New Project{% endblock %}

{% block content %}
{% crispy form %}
{% endblock %}

{% block custom_js %}
$('.datemask input')
// date masking
    .inputmask('yyyy-mm-dd', {"placeholder": "yyyy-mm-dd"})
// add calendar icon
    .wrap('<div class="input-group"></div>')
    .before('<div class="input-group-addon"><i class="fa fa-calendar"></i></div>');
// make workers field pretty
$('#id_workers').select2({
    minimumInputLength: 2,
});
$('#hint_id_workers').remove();
{% endblock %}

templates/pm/task.html
<table class="table task-list">
    <tr>
        <th></th>
        <th class="center vcenter" width="10%">Name</th>
        <th class="center vcenter">Description</th>
        <th class="center vcenter" width="10%">Start Date</th>
        <th class="center vcenter" width="10%">Due Date</th>
        <th class="center vcenter" width="10%">Completed Date</th>
        <th class="center vcenter" width="10%">Assigned To...</th>
        <th class="center vcenter" width="10%">Blocked by...</th>
    </tr>
    {% for task in project.task_set.all %}
    <tr class="task task-{{ task.pk }}">
        <td class="status center vcenter">
            <small class="badge {% if task.status = 'Active' %}bg-green active{% elif task.status = 'Complete' %}bg-blue complete{% else %}bg-yellow waiting{% endif %}">{{ task.status | linebreaksbr }}</small>
            <span class="edit"><button type="button" class="btn btn-sm btn-default"><i class="fa fa-pencil"></i></button></span>
            <span class="controls">
                <div class="btn-group">
                    <button type="button" class="btn btn-xs btn-default bg-green submit"><i class="fa fa-check"></i></button>
                    <button type="button" class="btn btn-xs btn-default bg-red cancel"><i class="fa fa-times"></i></button>
                </div>
            </span>
            <input type="hidden" name="pk" value="{{ task.pk }}">
            <input type="hidden" name="project" value="{{ task.project.pk }}">
            <input type="hidden" name="status" value="{{ task.status }}">
        </td>

        <td>
            <span class="txt">{{ task.name }}</span>
            <input type="text" name="name" value="{{ task.name }}">
        </td>
        <td>
            <span class="txt">{{ task.description | linebreaksbr }}</span>
            <textarea name="description" cols=50 rows=2>{{ task.description }}</textarea>
        </td>
        <td class="center datepicker">
            <span class="txt{% if task.start_date = None %} text-yellow{% endif %}">{{ task.start_date | default_if_none:'No date set' }}</span>
            <input type="text" name="start_date" value="{{ task.start_date | date:'m-d-Y' }}" size="11">
        </td>
        <td class="center datepicker">
            <span class="txt{% if task.due_date = None %} text-yellow{% endif %}">{{ task.due_date | default_if_none:'No date set' }}</span>
            <input type="text" name="due_date" value="{{ task.due_date | date:'m-d-Y' }}" size="11"><br class="input-help">
            <input class="checkboxinput checkbox" id="id_status_on_hold" name="status_on_hold" type="checkbox"{% if task.status_on_hold %} checked="checked"{% endif %}><span class="input-help"> On hold<br></span>
            <input class="checkboxinput checkbox" id="id_status_waiting" name="status_waiting" type="checkbox"{% if task.status_waiting %} checked="checked"{% endif %}><span class="input-help"> Waiting...</span>
        </td>
        <td class="center datepicker">
            <span class="txt">{{ task.date_complete | default_if_none:'' }}</span>
            <input type="text" name="date_complete" value="{{ task.date_complete | date:'m-d-Y' }}" size="11">
        </td>
        <td>
            <span class="txt">{% for taskworker in task.taskworker_set.all %}{{ taskworker.worker.person.full_name }}{% if not forloop.last %}, {% endif %}{% endfor %}</span>
            <select multiple="multiple" name="worker" size="3">
                {% for worker in task.project.worker_set.all %}<option value="{{ worker.person.pk }}">{{ worker.person.full_name }}</option>{% endfor %}
            </select>
        </td>
        <td>
            <span class="txt">{% for t in task.blocked_task.all %}{{ t.blocking_task.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</span>
            <select multiple="multiple" name="blocked_by" size="3">
                {% for t in task.project.task_set.all %}{% if t.pk != task.pk %}<option value="{{ t.pk }}">{{ t.name }}</option>{% endif %}{% endfor %}
            </select>
        </td>
    </tr>
    {% endfor %}
</table>